### ISSUE TITLE
can't build using browserify

### ISSUE THREAD

**Issue by pierrepinard** [instructure-react/react-menu#18]
Hi,

I am using the "master" branch, because the "reactify" browserify-transform is specified in package.json.

But it looks like last commit (https://github.com/instructure-react/react-menu/commit/3a012ab81ceb687c6a734e03ee07a89d40071b2b) prevents from building using browserify: required files in lib/index.js can't be found (probably because of the .js to .jsx renaming).
@trungpham could you please have a look at this?

Thanks,

**Comment by knomedia** [comment]
reverted the `jsx` extension stuff in https://github.com/instructure-react/react-menu/commit/07b01f531aa6e21d3feae38aa593daa147b28eb2 . browserify builds should be working

**Comment by pierrepinard** [comment]
@knomedia thank you very much, it works correctly indeed!
