### ISSUE TITLE
Update to support react 0.13.x

### ISSUE THREAD

**Issue by richardfickling** [instructure-react/react-menu#20]
It doesn't look like there were any breaking changes in 0.12.x -> 0.13.x that would stop react-menu from working with react 0.13.

**Comment by mitchellvanw** [comment]
I agree and have created a [PR for this](https://github.com/instructure-react/react-menu/pull/21).

**Comment by mitchellvanw** [comment]
@knomedia I think this one can be closed

**Comment by knomedia** [comment]
closed by #21
