### ISSUE TITLE
using injectCSS

### ISSUE THREAD

**Issue by Tredis** [instructure-react/react-menu#35]
I want to remove the border on the MenuTrigger. I have tried everything I can think of, but I just can't seem to affect the properties of the trigger.

What I've tried:
Menu.injectCSS({border: 'none'})
Menu.injectCSS({'border-style': 'none'})
Menu.injectCSS({Menu__MenuTrigger: {border: 'none'}})
Menu.injectCSS({MenuTrigger: {border: 'none'}})
Menu.injectCSS({Menu__MenuTrigger: {'border-style': 'none'}})
Menu.injectCSS({MenuTrigger: {'border-style': 'none'}})
Menu.injectCSS({".Menu__MenuTrigger": {border: 'none'}})
Menu.injectCSS({".Menu__MenuTrigger": {'border-style': 'none'}})
MenuTrigger.injectCSS({border: 'none'})
MenuTrigger.injectCSS({'border-style': 'none'})
Menu__MenuTrigger.injectCSS({border: 'none'})

It's quite frustrating not having an example of how to use the function in the readme.
I see you use jss, but doesn't seem to use the same signature as their injectSheet function

Please help, thanks

**Comment by mziwisky** [comment]
There _is_ an example of how to use injectCSS in the readme: `Menu.injectCSS();`

It doesn't take any arguments, it just applies default styling to the component by injecting a stylesheet into the document's head.  To override any of those defaults, just add your own stylesheet.
